version: '3'

services:
  app:
    image: paidy/forex:1.0.1
    ports:
      - "9000:9000"
    networks:
      - app-network
    depends_on:
      - one-frame
  one-frame:
    image: paidyinc/one-frame
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
